ci: add upgrade artifact actions (#6683)

diff --git a/.github/workflows/e2e-playwright.yml b/.github/workflows/e2e-playwright.yml
--- a/.github/workflows/e2e-playwright.yml
+++ b/.github/workflows/e2e-playwright.yml
@@ -1,4 +1,4 @@
-name: ⚙️ E2E tests
+name: ⚙️ Playwright E2E testing
 on:
   pull_request:
 
@@ -85,10 +85,10 @@ jobs:
         run: tree ${{ env.PLAYWRIGHT_SNAPSHOTS_PATH }}
 
       - name: Upload artifacts / ${{ env.PLAYWRIGHT_SNAPSHOTS_ARTIFACTS_KEY }}
-        uses: actions/upload-artifact@v3.1.3
+        uses: actions/upload-artifact@v4.3.0
         with:
           path: ./projects/demo-playwright/tests-results/**/*.diff.png
-          name: ${{ env.PLAYWRIGHT_SNAPSHOTS_ARTIFACTS_KEY }}
+          name: '${{ env.PLAYWRIGHT_SNAPSHOTS_ARTIFACTS_KEY }}_${{ matrix.shardIndex }}'
           if-no-files-found: ignore
           retention-days: 1
 
@@ -101,27 +101,22 @@ jobs:
       - uses: taiga-family/ci/actions/setup/checkout@v1.51.1
       - uses: taiga-family/ci/actions/setup/variables@v1.51.1
 
-      - name: Download artifacts / ${{ env.CYPRESS_SNAPSHOTS_ARTIFACTS_KEY }}
-        continue-on-error: true
-        uses: actions/download-artifact@v3.0.2
-        with:
-          name: ${{ env.CYPRESS_SNAPSHOTS_ARTIFACTS_KEY }}
-          path: ./total/cypress
-
       - name: Download artifacts / ${{ env.PLAYWRIGHT_SNAPSHOTS_ARTIFACTS_KEY }}
         continue-on-error: true
-        uses: actions/download-artifact@v3.0.2
+        uses: actions/download-artifact@v4.1.1
         with:
-          name: ${{ env.PLAYWRIGHT_SNAPSHOTS_ARTIFACTS_KEY }}
           path: ./total/playwright
+          pattern: ${{ env.PLAYWRIGHT_SNAPSHOTS_ARTIFACTS_KEY }}_*
+          merge-multiple: true
+      - run: ls -R ./total/playwright || echo "not found"
 
       - name: Check if diff-output exists
-        id: diff-checker
+        id: diff_checker
         run: |
           echo "diff_exist=$(find ./total -regex '.*diff\.png$' | wc -l | sed -e 's/^[[:space:]]*//')" >> $GITHUB_OUTPUT
 
       - name: Fall with an error if diff-output exists
-        if: ${{ steps.diff-checker.outputs.diff_exist != '0' }}
+        if: ${{ steps.diff_checker.outputs.diff_exist != '0' }}
         run: |
           find ./total -regex '.*diff\.png$' -exec echo "{}" \;
           exit 1
