ci: attach Cypress CT diff-snapshots to CI report (#9293)

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -1,6 +1,12 @@
-name: ⚙️ Playwright E2E testing
+name: ⚙️ E2E testing
 on:
   pull_request:
+
+env:
+  CYPRESS_BASELINE_REPO: 'baseline'
+  CYPRESS_RESULTS_FOLDER: 'projects/demo-cypress/tests-results'
+  CYPRESS_BASELINE_SNAPSHOTS: 'projects/demo-cypress/tests-results/snapshots/baseline'
+  CYPRESS_BASELINE_SNAPSHOTS_KEY: 'cy_baseline_${{ github.event.pull_request.head.sha }}'
 
 jobs:
   build-demo:
@@ -25,6 +31,60 @@ jobs:
           path: dist/demo
           key: ${{ env.CACHE_DIST_KEY }}
 
+  cypress:
+    runs-on: ubuntu-latest
+    name: Cypress / Component Testing
+    steps:
+      - uses: actions/checkout@v4.2.0
+        with:
+          ref: ${{ github.base_ref }}
+      - uses: taiga-family/ci/actions/setup/variables@v1.93.0
+      - uses: taiga-family/ci/actions/setup/node@v1.93.0
+
+      - name: Run tests for baseline state
+        run: npx nx component-test demo-cypress
+
+      - name: Save Cypress Baseline Snapshots
+        uses: actions/upload-artifact@v4.4.0
+        with:
+          path: ${{env.CYPRESS_BASELINE_SNAPSHOTS}}
+          name: ${{env.CYPRESS_BASELINE_SNAPSHOTS_KEY}}
+          if-no-files-found: ignore
+          compression-level: 0
+          retention-days: 1
+
+      - uses: actions/checkout@v4.2.0
+      - uses: taiga-family/ci/actions/setup/variables@v1.93.0
+      - uses: taiga-family/ci/actions/setup/node@v1.93.0
+
+      - name: Download Cypress Baseline Snapshots
+        uses: actions/download-artifact@v4.1.8
+        with:
+          path: ${{env.CYPRESS_BASELINE_SNAPSHOTS}}
+          pattern: ${{ env.CYPRESS_BASELINE_SNAPSHOTS_KEY }}
+          merge-multiple: true
+
+      - name: Run tests for current state
+        run: npx nx component-test demo-cypress
+
+      - name: Prepare diff screenshots
+        run: |
+          npm install canvas
+          npx ts-node ./scripts/visual-testing/combine-cypress-failed-screenshots.ts
+
+      - name: Debug output
+        continue-on-error: true
+        run: tree ${{ env.CYPRESS_RESULTS_FOLDER }}  -L 1
+
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4.4.0
+        with:
+          path: '${{ env.CYPRESS_RESULTS_FOLDER }}/**/*.diff.png'
+          name: ${{ env.CYPRESS_SNAPSHOTS_ARTIFACTS_KEY }}
+          if-no-files-found: ignore
+          compression-level: 0
+          retention-days: 1
+
   playwright:
     if: ${{ !contains(github.head_ref , 'release/') }}
     runs-on: ubuntu-latest
@@ -34,7 +94,7 @@ jobs:
       matrix:
         shardIndex: [1, 2, 3, 4, 5, 6, 7, 8, 9]
         shardTotal: [9]
-    name: playwright / (${{ matrix.shardIndex }} of ${{ matrix.shardTotal }})
+    name: Playwright / (${{ matrix.shardIndex }} of ${{ matrix.shardTotal }})
     steps:
       - uses: actions/checkout@v4.2.0
       - uses: taiga-family/ci/actions/setup/variables@v1.93.1
@@ -74,6 +134,7 @@ jobs:
       - name: Combine images to get diff reports
         run: |
           npm install canvas
+          npm view canvas version
           npx ts-node ./scripts/visual-testing/combine-playwright-failed-screenshots.ts
 
       - name: Debug output
@@ -112,13 +173,13 @@ jobs:
   result:
     if: ${{ !contains(github.head_ref , 'release/') }}
     name: E2E result
-    needs: [playwright]
+    needs: [playwright, cypress]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4.2.0
       - uses: taiga-family/ci/actions/setup/variables@v1.93.1
 
-      - name: Download artifacts / ${{ env.PLAYWRIGHT_SNAPSHOTS_ARTIFACTS_KEY }}
+      - name: Download artifacts for Playwright
         continue-on-error: true
         uses: actions/download-artifact@v4.1.8
         with:
@@ -126,6 +187,15 @@ jobs:
           pattern: ${{ env.PLAYWRIGHT_SNAPSHOTS_ARTIFACTS_KEY }}_*
           merge-multiple: true
       - run: ls -R ./total/playwright || echo "not found"
+
+      - name: Download artifacts for Cypress
+        continue-on-error: true
+        uses: actions/download-artifact@v4.1.8
+        with:
+          path: ./total/cypress
+          pattern: ${{ env.CYPRESS_SNAPSHOTS_ARTIFACTS_KEY }}
+          merge-multiple: true
+      - run: ls -R ./total/cypress || echo "not found"
 
       - name: Check if diff-output exists
         id: diff_checker
